version: 0.0
os: linux
files:
  - source: / #EC2에 복사할 파일
    destination: /home/market/server/ #EC2에 복사되는 파일의 위치
    overwrite: yes #덮어쓰기

permissions:
  - object: /
    pattern: "**"
    owner: market
    group: market

#hooks:
#  ApplicationStart: #CodeDeploy 생명 주기
#    - location: scripts/run_new_was.sh
#      timeout: 180
#      runas: market
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: market
#    - location: scripts/switch.sh
#      timeout: 180
#      runas: market