version: '3'
services:
  redis:
    container_name: market_redis
    image: redis:latest
    ports:
      - "6370:6379"
    networks:
      - db_network

  mysql:
    container_name: market_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: market
      MYSQL_USER: admin
      MYSQL_PASSWORD: market_pw
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3300:3306"
    networks:
      - db_network


networks:
  db_network:
    driver: bridge