spring:
  config:
    import:
      - classpath:/application-env.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(go7tA1gDWumqElU/NwTAYuYVIpPxLYkD7HBVVrrDD11lxzHD5Z2pgJItrrpZDMY35drR3wUg6pWOWbOiDYLkhXWS6gKRiUOMnz/hIncdG+byqU3QaUAJ9g==)
    username: ENC(18JjDEicgBjx75fWUy1y+g==)
    password: ENC(qFgoN0igRsC9TXBrnf6iNRMAiQEHffK1)

  redis:
    host: ENC(s2oyZoF87Ftu5nUTdauG+erBI5qrgQV6)
    port: ENC(tBdHkUaSchWYUfImNFCYNQ==)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace


