spring:
  config:
    import:
      - classpath:/application-env.yml
    activate:
      on-profile: "prod"
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 1GB
  data:
    web:
      pageable:
        default-page-size: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(n50uVPpI1HF/iRqlV9vHsXZ99owcmMTs80o5oMKH+ouPaeYvqFyYSo0GcsHZ2X3zLUOix6cRNWKYqZaJu28xQwspWybWJ+U2MwlDtLgdL0KOPK5Z+nqcTUigkzCfr3katopAhH4pNRqNIOYXpnyeMm4yHI81jDO3L3Ed5tacRcjiPijX8FzH+aiD8p26dfGngzF4YKL3lggFMXukyUhzeg==)
    username: ENC(ztwB9Bn21hiIPCeP6Vmm6w==)
    password: ENC(7tnQiKu3ss8yh5aQDjFbUYEmUphAaMXS)

  redis:
    host: ENC(x+D5O8la3FoqsdeT5nmxj2ColjOrmgB4)
    port: ENC(yL7BZSaEoaz12E/OKQuDWQ==)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  jwt:
    secret: ENC(5LmCYpeen2RivbMcI53zFLBDl4EhadF4HGzBLVfBdwJmAq7qLvBL3927ttjBTGnUdyeMDgEYfp4pLOhPv2TA11VnCokkIHK3GW3XiE3A5k5OuLmr1thQmzGF5o4npFuSgs55LIpOBoEPOlvv24ko7g==)

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

cloud:
  aws:
    s3:
      bucket: market---bucket
    credentials:
      access-key: ENC(+EUsHFVQLMKZ6oeLcfo9AOkDQ5a+f3DHlXpI0v+ZG7g=)
      secret-key: ENC(BUHYXUyC2n36a/hnjdGLm9wnilKaSaitJfGubsLpi7DaUwQCPyum0kx/YnvpT3/UFz3zj+NLn4w=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


