version: '3'
services:
  redis:
    container_name: market_redis_test
    image: redis:latest
    ports:
      - "6371:6379"
    networks:
      - db_test_network

  mysql:
    container_name: market_mysql_test
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: market
      MYSQL_USER: admin
      MYSQL_PASSWORD: market_pw
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3301:3306"
    networks:
      - db_test_network


networks:
  db_test_network:
    driver: bridge